### ISSUE TITLE
code hangs indefinitely

### ISSUE THREAD

**Issue by MareoRaft** [ghseeli/trunconomics#3]
Now in `main.py`, the following code causes the program to freeze:

        evaluator = TruncatorEvaluator()
        # TODO: stop test_file from freezing/hanging indefinitely
        out = evaluator.test_file(
            path.join(OUT_DIR, "out.csv"),
            "/System/Library/Fonts/Monaco.dfont"
        )

It is specifically the `test_file` function that gives issue.

**Comment by ghseeli** [comment]
This is very odd. The problem seems to stem from pygame's `pygame.font.Font` object being initialized in our `FontSizeCalculator`'s `size_of_string` method. It seems to be something involving loading the font. I have moved the font file into the repo and that has fixed it on my end. Can you please verify that it works on your end now? Then, I will remove the TODO. 

Also, this is a slow test because it is running on a huge number of words. It takes like 30--60 seconds on my Macbook Pro.

**Comment by MareoRaft** [comment]
Yeah, it works for me too. (5115b02de476be723226d234616fc3fe9b1d8d3f)
